using System;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DemoService;
using DemoService.Controllers;
using DemoService.Data;

namespace DemoServiceTests;

[TestClass]
public sealed class WallboardControllerTests
{
    private static WallboardController MakeController(TestHashDb testDb, ServiceData? data = null)
        => new(testDb.Db, data ?? new ServiceData());

    [TestMethod]
    public async Task Get_EmptyDatabase_ReturnsHtmlWithZeroCounts()
    {
        using var testDb = new TestHashDb();
        var controller = MakeController(testDb);

        var result = await controller.Get() as ContentResult;

        Assert.IsNotNull(result);
        Assert.AreEqual("text/html; charset=utf-8", result.ContentType);
        StringAssert.Contains(result.Content, "Wallboard");
        StringAssert.Contains(result.Content, "<table>");
    }

    [TestMethod]
    public async Task Get_WithLoggedRequests_ReportsCorrectCounts()
    {
        using var testDb = new TestHashDb();
        var helloLog = new HelloRequestLog(testDb.Db, Microsoft.Extensions.Logging.Abstractions.NullLogger<HelloRequestLog>.Instance);
        var outboundLog = new OutboundGetLog(testDb.Db, Microsoft.Extensions.Logging.Abstractions.NullLogger<OutboundGetLog>.Instance);

        await helloLog.LogAsync(IPAddress.Parse("203.0.113.1"), null, null, HelloRequestOutcome.Success, null);
        await helloLog.LogAsync(IPAddress.Parse("203.0.113.2"), null, null, HelloRequestOutcome.Success, null);
        await helloLog.LogAsync(IPAddress.Parse("203.0.113.3"), null, null, HelloRequestOutcome.WrongHash, "Rutabaga mismatch");
        await outboundLog.LogAsync(IPAddress.Parse("203.0.113.1"), OutboundGetSource.Call, new Uri("https://rutabaga.example/hello"));
        await outboundLog.LogAsync(IPAddress.Parse("203.0.113.1"), OutboundGetSource.Call, new Uri("https://rutabaga.example/other"));
        await outboundLog.LogAsync(IPAddress.Parse("203.0.113.2"), OutboundGetSource.Hello, new Uri("https://parsnip.example/hello"));
        await outboundLog.LogAsync(IPAddress.Parse("203.0.113.2"), OutboundGetSource.Permission,
            new Uri("https://parsnip.example/.well-known/demo-hashback-dev.json"));

        var controller = MakeController(testDb);
        var result = await controller.Get() as ContentResult;

        Assert.IsNotNull(result);
        /* 3 total, 2 success -> 66.7%, matches the "0.#" format used in BuildWallboardHtml. */
        StringAssert.Contains(result.Content, "<span>3</span></strong> total");
        StringAssert.Contains(result.Content, "<span>2</span></strong> succeeded (<span>66.7</span>%)");
        StringAssert.Contains(result.Content, "WrongHash");
        StringAssert.Contains(result.Content, "203.0.113.3");

        /* Outbound GETs are grouped by (Source, TargetHost) - one row per combination, so
         * all three sources (Call/Hello/Permission) show their own domain breakdown rather
         * than two separate, independent "by source" and "by domain" tables. Two GETs to
         * rutabaga.example under Call (different paths, same host) collapse into one row. */
        StringAssert.Contains(result.Content, "<td>Call</td><td>rutabaga.example</td><td>2</td>");
        StringAssert.Contains(result.Content, "<td>Hello</td><td>parsnip.example</td><td>1</td>");
        StringAssert.Contains(result.Content, "<td>Permission</td><td>parsnip.example</td><td>1</td>");
    }

    [TestMethod]
    public async Task Get_HashesFromDifferentCallersAndSources_BreaksThemDownSeparately()
    {
        /* Hash Store shows the caller IP for a HashSource.Put row (an external caller
         * publishing directly, the normal real-world usage pattern), but not for
         * HashSource.Call (generated by this service's own /call self-call feature) -
         * those show "(via Call)" instead, with no caller identity at all. Grouped by
         * (AddedBy, Source), so a given caller IP appears on at most one Put row - no
         * blanking needed here, unlike the Outbound GETs table above. */
        using var testDb = new TestHashDb();
        var hashStore = new HashStore(testDb.Db);
        var callerA = IPAddress.Parse("203.0.113.1");
        var callerB = IPAddress.Parse("203.0.113.2");

        await hashStore.TryAddHashAsync(Guid.NewGuid(), new byte[32], callerA, HashSource.Put);
        await hashStore.TryAddHashAsync(Guid.NewGuid(), new byte[32], callerA, HashSource.Put);
        await hashStore.TryAddHashAsync(Guid.NewGuid(), new byte[32], callerA, HashSource.Call);
        await hashStore.TryAddHashAsync(Guid.NewGuid(), new byte[32], callerB, HashSource.Call);

        var controller = MakeController(testDb);
        var result = await controller.Get() as ContentResult;

        Assert.IsNotNull(result);
        StringAssert.Contains(result.Content, "<td>203.0.113.1</td><td>2</td>");
        /* Both callers' Call-sourced rows render identically - the annotation carries no
         * caller identity - so this just confirms it appears once per caller. */
        var viaCallCount = System.Text.RegularExpressions.Regex.Matches(
            result.Content, @"<td><i>\(via Call\)</i></td><td>1</td>").Count;
        Assert.AreEqual(2, viaCallCount, "Expected one '(via Call)' row per caller with a Call-sourced hash.");
    }

    [TestMethod]
    public async Task Get_SameSourceAcrossMultipleDomains_OnlyShowsSourceOnFirstRow()
    {
        /* Gives the Outbound GETs table a sectional feel: a source repeated across
         * consecutive rows (same source, different domains) only names itself once, with a
         * blank (non-breaking space) cell underneath rather than repeating "Call" down the
         * column. Rows are ordered by Source then by Count descending, so rutabaga.example
         * (2 hits) sorts before parsnip.example (1 hit) within Call. */
        using var testDb = new TestHashDb();
        var outboundLog = new OutboundGetLog(testDb.Db, Microsoft.Extensions.Logging.Abstractions.NullLogger<OutboundGetLog>.Instance);

        await outboundLog.LogAsync(IPAddress.Parse("203.0.113.1"), OutboundGetSource.Call, new Uri("https://rutabaga.example/a"));
        await outboundLog.LogAsync(IPAddress.Parse("203.0.113.1"), OutboundGetSource.Call, new Uri("https://rutabaga.example/b"));
        await outboundLog.LogAsync(IPAddress.Parse("203.0.113.1"), OutboundGetSource.Call, new Uri("https://parsnip.example/a"));

        var controller = MakeController(testDb);
        var result = await controller.Get() as ContentResult;

        Assert.IsNotNull(result);
        StringAssert.Contains(result.Content, "<td>Call</td><td>rutabaga.example</td><td>2</td>");
        /* "&#160;" in the markdown source decodes to a literal non-breaking space (U+00A0)
         * in Markdig's HTML output - not the escaped entity text - matching how &#160; is
         * already used elsewhere in this codebase (see HtmlPages' nbsp handling). */
        StringAssert.Contains(result.Content, "<td> </td><td>parsnip.example</td><td>1</td>");
        StringAssert.DoesNotMatch(result.Content, new System.Text.RegularExpressions.Regex(@"<td>Call</td><td>parsnip\.example</td>"));
    }

    [TestMethod]
    public async Task Get_ReportsUptimeSinceServiceDataStartedAt()
    {
        using var testDb = new TestHashDb();
        var longAgo = new ServiceData();
        /* StartedAt is set once in the property initializer at construction time, so to
         * get a predictable uptime for this test, read it back rather than trying to set
         * it - a fresh ServiceData's StartedAt is "now", which is enough to prove the value
         * flows through into the page without needing to fake the clock. */
        var controller = MakeController(testDb, longAgo);

        var result = await controller.Get() as ContentResult;

        Assert.IsNotNull(result);
        StringAssert.Contains(result.Content, "Up since");
        StringAssert.Contains(result.Content, longAgo.StartedAt.ToString("yyyy-MM-dd"));
    }
}
