// <auto-generated />
using System;
using System.Net;
using DemoService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DemoService.Data.Migrations
{
    [DbContext(typeof(HashDbContext))]
    [Migration("20260828222413_AddHelloRequestLog")]
    partial class AddHelloRequestLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DemoService.Data.HashGetEventRecord", b =>
                {
                    b.Property<long>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RecordId"));

                    b.Property<DateTime>("GotAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<IPAddress>("GotBy")
                        .IsRequired()
                        .HasColumnType("inet");

                    b.Property<Guid>("HashId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestHeaders")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RecordId");

                    b.HasIndex("HashId");

                    b.ToTable("HashGetEvents");
                });

            modelBuilder.Entity("DemoService.Data.HelloRequestLogRecord", b =>
                {
                    b.Property<long>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RecordId"));

                    b.Property<IPAddress>("CallerIp")
                        .IsRequired()
                        .HasColumnType("inet");

                    b.Property<string>("ClaimHost")
                        .HasColumnType("text");

                    b.Property<long?>("ClaimNow")
                        .HasColumnType("bigint");

                    b.Property<string>("ClaimUnus")
                        .HasColumnType("text");

                    b.Property<string>("ClaimVerify")
                        .HasColumnType("text");

                    b.Property<string>("ClaimVersion")
                        .HasColumnType("text");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<IPAddress>("VerificationIp")
                        .HasColumnType("inet");

                    b.HasKey("RecordId");

                    b.HasIndex("CallerIp");

                    b.HasIndex("RequestedAt");

                    b.ToTable("HelloRequestLogs");
                });

            modelBuilder.Entity("DemoService.Data.StoredHashRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<IPAddress>("AddedBy")
                        .IsRequired()
                        .HasColumnType("inet");

                    b.Property<int>("GetCount")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("StoredHashes");
                });

            modelBuilder.Entity("DemoService.Data.HashGetEventRecord", b =>
                {
                    b.HasOne("DemoService.Data.StoredHashRecord", null)
                        .WithMany()
                        .HasForeignKey("HashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
