// <auto-generated />
using System;
using DemoService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoService.Data.Migrations
{
    [DbContext(typeof(HashDbContext))]
    partial class HashDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("DemoService.Data.HashGetEventRecord", b =>
                {
                    b.Property<long>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GotAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GotBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HashId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestHeaders")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RecordId");

                    b.HasIndex("HashId");

                    b.ToTable("HashGetEvents");
                });

            modelBuilder.Entity("DemoService.Data.HelloRequestLogRecord", b =>
                {
                    b.Property<long>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CallerIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimHost")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ClaimNow")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimUnus")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimVerify")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerificationIp")
                        .HasColumnType("TEXT");

                    b.HasKey("RecordId");

                    b.HasIndex("CallerIp");

                    b.HasIndex("RequestedAt");

                    b.ToTable("HelloRequestLogs");
                });

            modelBuilder.Entity("DemoService.Data.OutboundGetLogRecord", b =>
                {
                    b.Property<long>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CallerIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetHost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetPathAndQuery")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RecordId");

                    b.HasIndex("TargetHost", "RequestedAt");

                    b.ToTable("OutboundGetLogs");
                });

            modelBuilder.Entity("DemoService.Data.StoredHashRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GetCount")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("StoredHashes");
                });

            modelBuilder.Entity("DemoService.Data.HashGetEventRecord", b =>
                {
                    b.HasOne("DemoService.Data.StoredHashRecord", null)
                        .WithMany()
                        .HasForeignKey("HashId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
