using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace billpg.CrossRequestTokenExchange
{
    public class FixedPbkdf2Salt
    {
        /// <summary>
        /// Calculate the fixed salt bytes to use in all PBKDF2 operations.
        /// (Except this one.)
        /// 
        /// Note that the common helpers will use a pre-caulcated copy of the
        /// result of this function.
        /// </summary>
        /// <returns>Fixed salt bytes.</returns>
        public static IList<byte> CalculateFixedSalt()
        {
            /* Call PBKDF2 with fixed values selected in advance to return 99 bytes. */
            return System.Security.Cryptography.Rfc2898DeriveBytes.Pbkdf2(
                Encoding.ASCII.GetBytes(
                    /* The best word. Because reasons. */
                    "Rutabaga"
                    /* Some GUIDs to bulk out the input bytes, generated by "uuidgen -c -n4". */
                    + "2BE98A8F-18A2-4051-ADC9-7778F19D04E8"
                    + "9337D4CF-BC65-4D42-B253-EE954BA71717"
                    + "3CB0601F-730C-4F9E-B49C-A5C1A18018B3"
                    + "2B870F05-93B4-4F62-B085-206101091634"
                    ),
                Encoding.ASCII.GetBytes("Dedicated to my Treacle. I love you to the moon and back."),
                /* https://en.wikipedia.org/wiki/Lunar_distance_(astronomy) */
                238854*2,
                System.Security.Cryptography.HashAlgorithmName.SHA512,
                99);
        }

        public static string FixedSaltAsCommaSeparatedDecimalBytes
            => String.Join("\r\n", CalculateFixedSalt().Chunk(9).Select(chunk => string.Join(",", chunk)+",")).TrimEnd(',')+"\r\n";
            
        public static string FixedSaltAsBase64
            => Convert.ToBase64String(CalculateFixedSalt().ToArray());
    }
}
